# Valorant-optimized BoT-SORT configuration
                            # For documentation and examples see https://docs.ultralytics.com/modes/track/
                            # For BoT-SORT source code see https://github.com/NirAharon/BoT-SORT

                            tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
                            track_high_thresh: 0.5 # threshold for the first association
                            track_low_thresh: 0.1 # threshold for the second association
                            new_track_thresh: 0.6 # threshold for init new track if the detection does not match any tracks
                            track_buffer: 30 # buffer to calculate the time when to remove tracks
                            match_thresh: 0.8 # threshold for matching tracks
                            fuse_score: False # Whether to fuse confidence scores with the iou distances before matching

                            # BoT-SORT settings
                            gmc_method: sparseOptFlow # method of global motion compensation
                            # ReID model related thresh
                            proximity_thresh: 0.5 # minimum IoU for valid match with ReID
                            appearance_thresh: 0.25 # minimum appearance similarity for ReID
                            with_reid: True # Whether to use ReID
                            model: auto # uses native features if detector is YOLO else yolo11n-cls.pt
                            